-- Group color names for "Use group color names" feature (editable in Supabase)
-- Run in Supabase SQL Editor once. Edit rows in Table Editor to change the list.

CREATE TABLE IF NOT EXISTS color_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_color_names_sort ON color_names(sort_order);

-- Seed with default list only when table is empty (run once; then edit in Supabase as needed)
INSERT INTO color_names (name, sort_order)
SELECT * FROM (VALUES
('Red', 1), ('Orange', 2), ('Yellow', 3), ('Green', 4), ('Blue', 5), ('Purple', 6), ('Pink', 7), ('Gray', 8), ('Black', 9), ('White', 10),
('Cyan', 11), ('Magenta', 12), ('Violet', 13), ('Indigo', 14), ('Turquoise', 15), ('Teal', 16), ('Lime', 17), ('Olive', 18), ('Maroon', 19), ('Navy', 20),
('Crimson', 21), ('Scarlet', 22), ('Amber', 23), ('Coral', 24), ('Beige', 25), ('Copper', 26), ('Platinum', 27), ('Pearl', 28), ('Vermillion', 29), ('Ochre', 30),
('Chartreuse', 31), ('Periwinkle', 32), ('Fuchsia', 33), ('Mauve', 34), ('Lavender', 35), ('Lilac', 36), ('Mint', 37), ('Sage', 38), ('Jade', 39), ('Emerald', 40),
('Aquamarine', 41), ('Sapphire', 42), ('Cobalt', 43), ('Azure', 44), ('Cerulean', 45), ('Ultramarine', 46), ('Plum', 47), ('Burgundy', 48), ('Ruby', 49), ('Rose', 50),
('Salmon', 51), ('Peach', 52), ('Tangerine', 53), ('Apricot', 54), ('Mustard', 55), ('Lemon', 56), ('Canary', 57), ('Khaki', 58), ('Tan', 59), ('Taupe', 60),
('Sienna', 61), ('Auburn', 62), ('Mahogany', 63), ('Chestnut', 64), ('Marigold', 65), ('Saffron', 66), ('Citrine', 67), ('Viridian', 68), ('Moss', 69), ('Celadon', 70),
('Seafoam', 71), ('Aqua', 72), ('Prussian', 73), ('Orchid', 74), ('Amaranth', 75), ('Carmine', 76), ('Cerise', 77), ('Cardinal', 78), ('Garnet', 79), ('Wine', 80),
('Mulberry', 81), ('Heather', 82), ('Ash', 83), ('Charcoal', 84), ('Slate', 85), ('Onyx', 86)
) AS v(name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM color_names LIMIT 1);

-- Allow read for authenticated users (adjust RLS as needed for your project)
ALTER TABLE color_names ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read color_names for authenticated"
ON color_names FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow read color_names for anon if needed"
ON color_names FOR SELECT
TO anon
USING (true);

-- Allow service role / full access for edits in dashboard
CREATE POLICY "Allow all for service role"
ON color_names FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

COMMENT ON TABLE color_names IS 'Editable list of color names for group labels (Use group color names).';
